language: crystal

crystal:
  - latest
  - nightly

jobs:
  allow_failures:
    - crystal: nightly

install:
  - shards install

script:
  - crystal spec
  - crystal tool format --check
  - crystal bin/ameba.cr
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: docs
  github_token: $GITHUB_TOKEN